FROM local/shlink

ADD https://www.digicert.com/CACerts/BaltimoreCyberTrustRoot.crt.pem /etc/ssl/certs/azure.pem
ADD https://dl.cacerts.digicert.com/DigiCertGlobalRootCA.crt.pem /etc/ssl/certs/azure-cn.pem
ADD https://www.d-trust.net/cgi-bin/D-TRUST_Root_Class_3_CA_2_2009.crt /etc/ssl/certs/azure-de.pem
