stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build_Shlink_Docker_Image
    displayName: Build Shlink docker image
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          docker pull shlinkio/shlink:$(shlinkVersion)
        displayName: 'Pull shlink image version $(shlinkVersion)'

      - script: |
          docker save shlinkio/shlink:$(shlinkVersion) | gzip > $(Agent.BuildDirectory)/s/shlink.tar.gz
        displayName: 'Create image archive'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish image'
        inputs:
          targetPath: '$(Agent.BuildDirectory)/s/shlink.tar.gz'
