stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build_Shlink_Docker_Image
    displayName: Build Shlink docker image
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          echo "##vso[build.updatebuildnumber]$(shlinkVersion)-$(Build.BuildNumber)"
        displayName: Rename build - $(shlinkVersion)-$(Build.BuildNumber)

      - script: |
          #docker pull shlinkio/shlink:$(shlinkVersion)
          docker built -t local/shlink .
        displayName: 'Pull shlink image version $(shlinkVersion)'

      - script: |
          docker build -t shlinkio/shlink:$(Build.BuildNumber) azure
          docker save shlinkio/shlink:$(Build.BuildNumber) | gzip > $(Agent.BuildDirectory)/s/shlink.tar.gz
        displayName: 'Create image archive'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish image'
        inputs:
          targetPath: '$(Agent.BuildDirectory)/s/shlink.tar.gz'
          artifactName: 'shlink'
