version: '2'
services:
  db:
    build: mysql-ssl
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"

  shlink:
    build: .
    environment:
      - "DB_DRIVER=mysql"
      - "DB_USER=test"
      - "DB_PASSWORD=test"
      - "DB_NAME=test"
      - "DB_HOST=db"
      - "DB_PORT=3306"
    depends_on:
      - db
